// Phase 6 — Blender export: session JSON → Blender Python script
// Usage: npx tsx generate.ts <session.json> [--fps 30] [--include-camera] [--out out.py]

import * as fs from "fs";
import * as path from "path";

// --- Types matching session schema ---

interface PoseSample {
  t: number;
  p: [number, number, number];
  q: [number, number, number, number]; // [x, y, z, w]
  tracking: string;
  trackingReason?: string;
}

interface Marker {
  t: number;
  label: string;
}

interface Session {
  version: number;
  id: string;
  createdAt: string;
  device: {
    model: string;
    iosVersion: string;
    hasLiDAR: boolean;
    screen: { width: number; height: number; scale: number };
  };
  pose: PoseSample[];
  imu: unknown[];
  touches: unknown[];
  markers: Marker[];
  video?: {
    filename: string;
    startOffsetMs: number;
    fps: number;
    codec: string;
    width: number;
    height: number;
  };
  mesh?: { filename: string };
  duration: number;
}

// --- Arg parsing ---

function parseArgs(argv: string[]): {
  sessionPath: string;
  fps: number;
  includeCamera: boolean;
  outPath: string | null;
} {
  const args = argv.slice(2);
  let sessionPath = "";
  let fps = 30;
  let includeCamera = false;
  let outPath: string | null = null;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--fps") {
      i++;
      const val = parseInt(args[i], 10);
      if (isNaN(val) || val <= 0) {
        console.error("--fps must be a positive integer");
        process.exit(1);
      }
      fps = val;
    } else if (arg === "--include-camera") {
      includeCamera = true;
    } else if (arg === "--out") {
      i++;
      outPath = args[i];
    } else if (!arg.startsWith("--") && sessionPath === "") {
      sessionPath = arg;
    }
  }

  if (!sessionPath) {
    console.error(
      "Usage: npx tsx generate.ts <session.json> [--fps 30] [--include-camera] [--out out.py]"
    );
    process.exit(1);
  }

  return { sessionPath, fps, includeCamera, outPath };
}

// --- Decimation: pick pose samples at target fps intervals ---

interface DecimatedFrame {
  frame: number;
  p: [number, number, number];
  q: [number, number, number, number]; // [x, y, z, w] from JSON
}

function decimatePoses(
  poses: PoseSample[],
  fps: number
): DecimatedFrame[] {
  if (poses.length === 0) return [];

  const intervalMs = 1000 / fps;
  const result: DecimatedFrame[] = [];
  let nextTargetMs = 0;
  let poseIdx = 0;

  // Walk through time at fps intervals, pick the nearest pose sample
  const maxT = poses[poses.length - 1].t;
  // Use a small epsilon to avoid missing the last sample due to floating-point
  const epsilon = intervalMs * 0.5;

  while (nextTargetMs <= maxT + epsilon) {
    // Advance poseIdx to the sample closest to nextTargetMs
    while (
      poseIdx < poses.length - 1 &&
      Math.abs(poses[poseIdx + 1].t - nextTargetMs) <=
        Math.abs(poses[poseIdx].t - nextTargetMs)
    ) {
      poseIdx++;
    }

    const sample = poses[poseIdx];
    const frame = Math.round(nextTargetMs / 1000 * fps);

    result.push({
      frame,
      p: sample.p,
      q: sample.q,
    });

    nextTargetMs += intervalMs;
  }

  return result;
}

// --- Python script generation ---

function generatePythonScript(
  session: Session,
  frames: DecimatedFrame[],
  fps: number,
  includeCamera: boolean
): string {
  const maxFrame = frames.length > 0 ? frames[frames.length - 1].frame : 0;
  const sessionId = session.id;

  // Build the data list as a Python literal
  const dataLines = frames.map((f) => {
    const [x, y, z, w] = f.q;
    // Store as (frame, (px, py, pz), (qx, qy, qz, qw)) — JSON order
    return `    (${f.frame}, (${f.p[0]}, ${f.p[1]}, ${f.p[2]}), (${x}, ${y}, ${z}, ${w})),`;
  });

  // Build markers list as Python literal
  const markerLines = session.markers.map((m) => {
    const escapedLabel = m.label.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
    return `    ('${escapedLabel}', ${m.t}),`;
  });

  return `# Blender Python script generated from session: ${sessionId}
# Run this in Blender's Scripting tab (open file, then click Run Script).
# Generated by phone-mocap-native Blender exporter.

import bpy
import math
import mathutils


# --- Coordinate conversion helpers ---

def pos_arkit_to_blender(p):
    """Position (x, y, z) ARKit -> (x, -z, y) Blender."""
    return (p[0], -p[2], p[1])


def quat_json_to_blender(q):
    """Convert quaternion from JSON [x, y, z, w] to Blender frame.

    Reorders from JSON (x,y,z,w) to Blender (w,x,y,z), then applies
    the frame-change rotation (-90 deg around X) to go from ARKit Y-up
    to Blender Z-up.
    """
    x, y, z, w = q
    q_arkit = mathutils.Quaternion((w, x, y, z))
    q_change = mathutils.Quaternion((math.sqrt(2) / 2, math.sqrt(2) / 2, 0, 0))
    return q_change @ q_arkit


# --- Session data ---

FPS = ${fps}
SESSION_ID = '${sessionId}'

# Each entry: (frame, (px, py, pz), (qx, qy, qz, qw))
# Positions and quaternions are in ARKit frame (JSON).
KEYFRAMES = [
${dataLines.join("\n")}
]

MARKERS = [
${markerLines.join("\n")}
]


# --- Scene setup ---

collection = bpy.data.collections.new(SESSION_ID)
bpy.context.scene.collection.children.link(collection)

bpy.ops.object.empty_add(type='PLAIN_AXES')
rig = bpy.context.active_object
rig.name = 'mocap_rig'

# Move from default collection to session collection
for col in rig.users_collection:
    col.objects.unlink(rig)
collection.objects.link(rig)

rig.rotation_mode = 'QUATERNION'

bpy.context.scene.render.fps = FPS
bpy.context.scene.frame_start = 0
bpy.context.scene.frame_end = ${maxFrame}


# --- Insert keyframes ---

for frame, pos, quat in KEYFRAMES:
    bpy.context.scene.frame_set(frame)
    rig.location = pos_arkit_to_blender(pos)
    q_blender = quat_json_to_blender(quat)
    rig.rotation_quaternion = (q_blender.w, q_blender.x, q_blender.y, q_blender.z)
    rig.keyframe_insert(data_path='location', frame=frame)
    rig.keyframe_insert(data_path='rotation_quaternion', frame=frame)

${includeCamera ? `
# --- Camera ---

bpy.ops.object.camera_add()
cam = bpy.context.active_object
cam.name = 'mocap_camera'
cam.parent = rig
cam.data.lens = 24  # ~iPhone wide camera equivalent focal length

# Move from default collection to session collection
for col in cam.users_collection:
    col.objects.unlink(cam)
collection.objects.link(cam)
` : "# Camera not included (use --include-camera to add one)."}

# --- Timeline markers ---

for label, t_ms in MARKERS:
    marker_frame = round(t_ms / 1000 * FPS)
    bpy.context.scene.timeline_markers.new(label, frame=marker_frame)


# --- Done ---

bpy.context.scene.frame_set(0)
print(f"Imported {len(KEYFRAMES)} keyframes for session {SESSION_ID}")
`;
}

// --- Main ---

function main(): void {
  const { sessionPath, fps, includeCamera, outPath } = parseArgs(process.argv);

  const resolvedPath = path.resolve(sessionPath);
  if (!fs.existsSync(resolvedPath)) {
    console.error(`Session file not found: ${resolvedPath}`);
    process.exit(1);
  }

  const raw = fs.readFileSync(resolvedPath, "utf-8");
  const session: Session = JSON.parse(raw);

  if (!session.pose || session.pose.length === 0) {
    console.error("Session contains no pose data.");
    process.exit(1);
  }

  // Sort poses by timestamp (spec says don't assume monotonic)
  session.pose.sort((a, b) => a.t - b.t);

  const frames = decimatePoses(session.pose, fps);

  const script = generatePythonScript(session, frames, fps, includeCamera);

  const outputPath = outPath
    ? path.resolve(outPath)
    : path.resolve(`${session.id}.py`);

  fs.writeFileSync(outputPath, script, "utf-8");
  console.log(
    `Wrote ${frames.length} keyframes at ${fps} fps to ${outputPath}`
  );
}

main();
